#!/bin/bash

_DISK_ () {

    [ -z "$2" ] && icon="" || icon="$2"

    disk_usage=$(df -h "$1" | awk '/\/dev\//{print $3"i/"$2"i"}');
    echo "$icon $disk_usage"
}

case $1 in
	1 )
		[ "$#" -gt "1" ] && {echo " $0 : To many Argument " && return 0 }
	    _DISK_ "$2" "$3"
		;;
esac
