#!/bin/sh

load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

# full text
echo "   $load  "

# short text
echo "   $load  "

# color if load is too high
awk -v cpus=$cpus -v cpuload=$load '
    BEGIN {
        if (cpus <= cpuload) {
            print "#6F8047\n";
            exit 33;
        }
    }
'
