#!/bin/sh

TYPE="${BLOCK_INSTANCE:-mem}"

awk -v type=$TYPE '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	if (type == "swap") {
		free=swap_free/1024/1024
		used=(swap_total-swap_free)/1024/1024
		total=swap_total/1024/1024
	} else {
		free=mem_free/1024/1024
		used=(mem_total-mem_free)/1024/1024
		total=mem_total/1024/1024
	}
	pct=used/total*100

	# full text
	printf("%.1fGi/%.1fGi\n", used, total)

	# short text
	printf("%.f%%\n", pct)

	# color
	if (pct > 90) {
		print("#BA2922\n")
	} else if (pct > 80) {
		print("#6F8047\n")
	} else if (pct > 70) {
		print("#586E75\n")
	} else if (pct > 0) {
		print("#9eb15c\n")
	}
}
' /proc/meminfo
