#!/bin/bash
#Show Machine Uptime - 10 (uptime)
_UPTIME_ () {

    [ -z "$1" ] && icon="" || icon="$1"

    uptime=$(uptime -p \
	| sed -E 's/ hours,/h/g; s/ hour,/h/g; s/ minutes/m/g; s/ minutes,/m/g; s/ minute,/m/g; s/ minute,/m/g; s/ days,/d/g; s/ day,/d/g; s/up //g') 

    echo "$icon $uptime"
}

case $1 in
	1 )
	[ "$#" -gt "1" ] && {echo " $0 : To many Argument " && return 0 }
	    _UPTIME_ "$2"
	;;
esac
